# Site settings
title: 50%渣男
email: 446100240@qq.com
description: "现在还没什么可描述自己的，不断变得更强，以后再改描述"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  kfeng123

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge